remote_theme : Jseongwon/Jseongwon.github.io
url: "https://yourname.github.io" # the base hostname & protocol for your site e.g. "https://Jseongwon.github.io"
baseurl: "" # the subpath of your site, e.g. /blog
